basePath: /
definitions:
  model.RightDTO:
    properties:
      code:
        type: string
      description:
        type: string
      id:
        type: integer
      is_attached:
        type: boolean
      section:
        type: string
    type: object
  model.RoleDTO:
    properties:
      code:
        type: string
      description:
        type: string
      id:
        type: integer
      is_attached:
        type: boolean
      name:
        type: string
      rights:
        items:
          $ref: '#/definitions/model.RightDTO'
        type: array
      status:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      id:
        type: integer
      last_name:
        type: string
      login:
        type: string
      name:
        type: string
      password:
        type: string
      roles:
        items:
          $ref: '#/definitions/model.RoleDTO'
        type: array
      status:
        type: string
      surname:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Swagger Example API
  version: "2.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /ping:
    get:
      consumes:
      - application/json
      description: Ping.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Ping pong
      tags:
      - root
  /users/:
    get:
      consumes:
      - application/json
      description: Get All Users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get All Users
    post:
      consumes:
      - application/json
      description: Add by json user
      parameters:
      - description: Add user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Add an user
      tags:
      - users
schemes:
- http
swagger: "2.0"
